### ISSUE TITLE
Incorrect benchmark for dense operator addition in Python

### ISSUE THREAD

**Issue by akhmerov** [qojulia/QuantumOptics.jl-benchmarks#3]
Contrary to the description, the file below tests the timing of addition of two sparse matrices and not dense ones.

https://github.com/qojulia/QuantumOptics.jl-benchmarks/blob/master/benchmarks-QuTiP/addition_dense_dense.py

**Comment by akhmerov** [comment]
Same applies to dense multiplication—the Python version isn't dense.

**Comment by david-pl** [comment]
That is quite the copy-paste error you found there, thanks. I changed the code where necessary.
